name: Accessibility Audit on PR

on:
  pull_request:
    branches: [main]

jobs:
  accessibility:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build React App
        run: npm run build

      - name: Serve App Locally
        run: |
          npm install -g serve
          serve -s build -l 5000 &  # Serve static build folder at port 5000
          npx wait-on http://localhost:5000

      - name: Install Pa11y
        run: npm install -g pa11y

      - name: Run Accessibility Audit
        run: pa11y http://localhost:5000 --reporter html > pa11y-report.html

      - name: Upload Accessibility Report
        uses: actions/upload-artifact@v4
        with:
          name: pa11y-report
          path: pa11y-report.html
