name: Accessibility Audit

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  accessibility:
    name: Run Accessibility Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Project Dependencies
        run: npm ci

      - name: Build Vite App
        run: npm run build

      - name: Install wait-on and pa11y
        run: npm install -g wait-on pa11y

      - name: Start Vite Preview Server
        run: |
          npm run preview &  # Starts Vite preview server (usually on port 4173)
          wait-on http://localhost:4173

      - name: Run Pa11y Accessibility Audit
        run: pa11y http://localhost:4173 --reporter html > pa11y-report.html

      - name: Upload Accessibility Report
        uses: actions/upload-artifact@v4
        with:
          name: pa11y-report
          path: pa11y-report.html
